cmake_minimum_required(VERSION 4.1)
project(C___Study)

set(CMAKE_CXX_STANDARD 11)

add_executable(C___Study Bases/hello.cpp)
add_executable(format Bases/format.cpp)
add_executable(defaultPara Bases/defaultPara.cpp)
add_executable(overloadFunc Bases/overloadFunc.cpp)
add_executable(quote Bases/quote.cpp)
add_executable(StringBase Bases/StringBase.cpp)
add_executable(alloMemory Bases/alloMemory.cpp)
add_executable(typeCast Bases/typeCast.cpp)

add_executable(student ClassAndObjection/student.cpp)
add_executable(package ClassAndObjection/package.cpp)
add_executable(constructFunc ClassAndObjection/constructFunc.cpp)
add_executable(People ClassAndObjection/People.cpp)
add_executable(Rabbit ClassAndObjection/Rabbit.cpp)
add_executable(copy ClassAndObjection/copy.cpp)
add_executable(const ClassAndObjection/const.cpp)
add_executable(staticFunc ClassAndObjection/staticFunc.cpp)
add_executable(friendFunc ClassAndObjection/friendFunc.cpp)
add_executable(friendClass ClassAndObjection/friendClass.cpp)

add_executable(bank Projects/bank.cpp)

add_executable(operatorPlus operatorReload/operatorPlus.cpp)
add_executable(operatorCommon operatorReload/operatorCommon.cpp)
add_executable(operateAndConstructorCast operatorReload/operateAndConstructorCast.cpp)
add_executable(operatorFunc operatorReload/operatorFunc.cpp)
add_executable(refCount operatorReload/refCount.cpp)
add_executable(countSmart operatorReload/countSmart.cpp)
add_executable(virtualInherit Inherit/virtualInherit.cpp)
add_executable(derive Inherit/derive.cpp)
add_executable(public Inherit/public.cpp)
add_executable(compatibility Inherit/compatibility.cpp)
add_executable(conDestructor Inherit/conDestructor.cpp)
add_executable(overWrite Inherit/overWrite.cpp)
add_executable(multiInherit Inherit/multiInherit.cpp)
add_executable(triagnle Inherit/triagnle.cpp)
add_executable(diamond Inherit/diamond.cpp)